### ISSUE TITLE
245px and 160px photosets

### ISSUE THREAD

**Issue by MitchellIB** [pixelunion/Extended-Tumblr-Photoset#20]
When I post photosets of different sizes they're all on separate lines leaving a lot of empty space next to them in the container. Do you know a way to make multiple images appear on the same line using your code if they're small enough?
The issue comes from photosets of size 245px and 160px
Thanks

**Comment by jarednorman** [comment]
Do you have an example of exactly what you're experiencing?

**Comment by MitchellIB** [comment]
I essentially want these pictures to be on the same line if they fit http://that-the-powerful-play-goes-on.tumblr.com/post/84677660316/apiphile-forever-sad-he-didnt-retire-to-farm

**Comment by jarednorman** [comment]
You haven't correctly installed the photoset plugin. You'll notice if you open up the Chrome developer console on that page that there are a few errors. The photoset code is failing to load, and then the call to the photoset plugin is failing because it isn't loaded, obviously. 

The photoset plugin is designed to lay the photoset almost _exactly_ the same way that the normal Tumblr photoset layout does, which is to say that it lays the photoset out the way it was laid out when the post was created. If it were working, both those images would be stretched to full width and they would be stacked.
